Get devices for measurement successfully!
#### # Linerar 32 3072 768
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_32_3072_output_0_32_768_in_features_3072_out_features_768.json
#### Find tuned kernel, pass
linear_kernel<function CUDACompiler.create_raw.<locals>.func at 0x7f8c78817790>
Traceback (most recent call last):
  File "linear_3078_768.py", line 100, in <module>
    time = Timer(
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 266, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 21, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: (tensor([[-0.0502, -0.7909, -1.7689,  ...,  0.9432, -1.8473, -0.9596],
        [-0.1640,  0.5327, -0.4981,  ..., -1.3619,  0.0736, -0.5741],
        [ 0.3023, -0.5829,  0.9101,  ...,  0.8569, -0.5747,  1.1916],
        ...,
        [-0.8948,  0.2453, -0.8498,  ..., -0.8065, -1.9526, -1.1819],
        [-1.1079,  0.2813, -0.1988,  ...,  0.1897,  1.2815, -1.2709],
        [-1.3601,  0.9480, -1.1432,  ..., -0.8735,  0.4418,  0.0595]],
       device='cuda:0'), Parameter containing:
tensor([[ 0.0099, -0.0174,  0.0151,  ..., -0.0128, -0.0124,  0.0162],
        [-0.0001,  0.0026,  0.0168,  ...,  0.0118, -0.0130,  0.0109],
        [ 0.0002,  0.0072,  0.0107,  ..., -0.0114, -0.0040,  0.0110],
        ...,
        [-0.0162,  0.0146,  0.0022,  ...,  0.0123, -0.0120, -0.0127],
        [-0.0054,  0.0022,  0.0097,  ..., -0.0051,  0.0122, -0.0062],
        [ 0.0064,  0.0179,  0.0091,  ..., -0.0053,  0.0134,  0.0040]],
       device='cuda:0', requires_grad=True), tensor([[       nan,        nan, 0.0000e+00,  ..., 4.5755e-41, 0.0000e+00,
         0.0000e+00],
        [       nan,        nan, 0.0000e+00,  ...,        nan, 0.0000e+00,
         0.0000e+00],
        [       nan,        nan, 0.0000e+00,  ...,        nan, 0.0000e+00,
         0.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]], device='cuda:0'), None), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7f8d100d5700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7f8c787f43a0>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7f8dbd165c10>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
