Get devices for measurement successfully!
#### # Linerar 192 768 3072
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_768_output_0_192_3072_in_features_768_out_features_3072.json
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_768_output_0_192_3072_in_features_768_out_features_3072.json
#### Find tuned kernel, pass
linear_kernel<function CUDACompiler.create_raw.<locals>.func at 0x7f8f58d6fc10>
Type of x: <class 'torch.Tensor'>
Type of weight: <class 'torch.nn.parameter.Parameter'>
Type of y: <class 'torch.Tensor'>
Type of bias: <class 'NoneType'>
Traceback (most recent call last):
  File "linear_3078_768.py", line 113, in <module>
    time = Timer(
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 266, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 21, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: ([tensor([[ 0.8888,  0.0672, -0.1119,  ...,  1.5824, -0.4836,  0.0516],
        [ 0.1408, -0.7565, -0.4228,  ...,  0.6055,  0.4478,  1.3032],
        [-0.2327, -0.7875,  0.7124,  ..., -0.9863, -0.6741, -0.7101],
        ...,
        [ 1.6989,  0.2429,  0.8282,  ..., -0.2888,  1.2230, -1.0375],
        [-0.5546,  1.3970,  0.8669,  ...,  1.0723, -0.1046, -0.5033],
        [ 0.8806, -0.1011, -1.8380,  ..., -0.6060,  0.2904, -0.2367]],
       device='cuda:0')], [Parameter containing:
tensor([[ 0.0300, -0.0233, -0.0106,  ...,  0.0183,  0.0211,  0.0071],
        [-0.0112, -0.0122, -0.0194,  ...,  0.0185,  0.0162,  0.0298],
        [ 0.0021,  0.0134, -0.0293,  ...,  0.0285, -0.0225,  0.0331],
        ...,
        [ 0.0059,  0.0337, -0.0196,  ..., -0.0118, -0.0090,  0.0269],
        [ 0.0296,  0.0323,  0.0101,  ..., -0.0225, -0.0116,  0.0106],
        [-0.0193,  0.0331, -0.0146,  ..., -0.0057,  0.0326, -0.0297]],
       device='cuda:0', requires_grad=True)], tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0'), [None]), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7f8eb02b2790>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7f8e1934b430>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7f8f5dcb2ca0>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
