Get devices for measurement successfully!
#### # Linerar 32 3072 768
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_32_3072_output_0_32_768_in_features_3072_out_features_768.json
#### Find tuned kernel, pass
linear_kernel<function CUDACompiler.create_raw.<locals>.func at 0x7f6db045d790>
Traceback (most recent call last):
  File "linear_3078_768.py", line 100, in <module>
    time = Timer(
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 266, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 21, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: (tensor([[-0.3002, -0.0079, -0.2486,  ..., -0.3059, -0.3207,  0.1543],
        [-1.5446,  0.0923, -0.5741,  ..., -1.0193, -1.8111,  0.6454],
        [-0.5557, -1.1820, -0.8146,  ..., -2.4260, -0.6967,  1.7926],
        ...,
        [ 0.3587,  0.4806,  1.2455,  ...,  1.7308,  0.5303,  0.3273],
        [-0.4806, -0.7001,  1.3809,  ...,  0.1623, -0.2602, -1.6930],
        [-0.0333,  0.2310, -0.0455,  ..., -1.1180, -0.1567, -1.1522]],
       device='cuda:0'), Parameter containing:
tensor([[-0.0014, -0.0155, -0.0168,  ...,  0.0002, -0.0071, -0.0082],
        [-0.0056, -0.0128, -0.0046,  ..., -0.0064,  0.0119, -0.0130],
        [-0.0075, -0.0148,  0.0164,  ..., -0.0146, -0.0022,  0.0165],
        ...,
        [-0.0017, -0.0123,  0.0026,  ...,  0.0111,  0.0018, -0.0174],
        [-0.0019,  0.0063, -0.0131,  ..., -0.0152, -0.0074, -0.0021],
        [ 0.0136,  0.0164, -0.0163,  ...,  0.0061,  0.0009, -0.0044]],
       device='cuda:0', requires_grad=True), tensor([[1.1596e+36, 4.5715e-41, 1.2454e-04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [7.6914e-01, 4.5712e-41, 0.0000e+00,  ...,        nan, 0.0000e+00,
         0.0000e+00],
        [5.8156e-11, 4.5712e-41, 0.0000e+00,  ...,        nan, 0.0000e+00,
         0.0000e+00],
        ...,
        [       nan,        nan, 0.0000e+00,  ...,        nan, 0.0000e+00,
         0.0000e+00],
        [       nan,        nan, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]], device='cuda:0'), None), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7f6db1cab700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7f6db043a3a0>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7f6ef4da1c10>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
