Get devices for measurement successfully!
#### # Linerar 32 3072 768
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_32_3072_output_0_32_768_in_features_3072_out_features_768.json
#### Find tuned kernel, pass
linear_kernel<function CUDACompiler.create_raw.<locals>.func at 0x7ff5293ff790>
Traceback (most recent call last):
  File "linear_3078_768.py", line 100, in <module>
    time = Timer(
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 266, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 21, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: (tensor([[ 0.1940, -0.1894,  0.4395,  ...,  0.7070, -0.5006,  1.0124],
        [-1.7992, -1.0811,  0.1131,  ..., -1.0760, -0.7630, -1.3169],
        [ 0.1570,  0.8082, -0.2721,  ...,  1.0129,  0.5125, -0.4538],
        ...,
        [-0.5432, -1.7605,  1.4833,  ..., -0.5117,  1.0596,  1.5132],
        [ 1.1087,  0.0925, -0.4536,  ..., -1.3045,  0.6957, -2.7103],
        [-0.9036, -1.1428,  0.9869,  ...,  1.1063, -0.6400, -0.3182]],
       device='cuda:0'), Parameter containing:
tensor([[ 0.0097, -0.0107, -0.0019,  ...,  0.0001, -0.0033,  0.0065],
        [ 0.0017, -0.0090, -0.0160,  ..., -0.0031, -0.0025,  0.0083],
        [ 0.0060, -0.0016, -0.0065,  ...,  0.0153,  0.0086,  0.0167],
        ...,
        [ 0.0005, -0.0085, -0.0048,  ...,  0.0138, -0.0091,  0.0034],
        [-0.0069, -0.0013, -0.0026,  ...,  0.0021, -0.0077,  0.0053],
        [-0.0153,  0.0032,  0.0054,  ..., -0.0161, -0.0010, -0.0129]],
       device='cuda:0', requires_grad=True), tensor([[5.5107e-14, 2.3305e-09, 1.4410e-19,  ..., 7.5555e+31, 4.6042e+30,
         9.3545e+05],
        [1.4155e+34, 1.4071e-19, 1.4225e-13,  ..., 1.8040e+28, 4.6121e+24,
         1.6631e+22],
        [5.6478e-11, 5.5567e-16, 1.4331e-19,  ..., 1.2706e+25, 5.3702e+31,
         2.6453e+20],
        ...,
        [4.3198e+27, 3.0101e+32, 3.5455e+12,  ..., 1.8521e+34, 1.4355e-19,
         3.9330e-14],
        [9.5466e-06, 1.4333e-19, 1.7055e-07,  ..., 2.6800e+20, 6.4288e+16,
         9.3346e-15],
        [7.5555e+31, 4.6042e+30, 9.3545e+05,  ..., 2.3308e-09, 7.6203e+17,
         1.9827e+29]], device='cuda:0'), None), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7ff5c0339700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7ff5293dd3a0>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7ff66dd48c10>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
