Get devices for measurement successfully!
#### # Linerar 192 768 3072
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_768_output_0_192_3072_in_features_768_out_features_3072.json
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_768_output_0_192_3072_in_features_768_out_features_3072.json
#### Find tuned kernel, pass
linear_kernel<function CUDACompiler.create_raw.<locals>.func at 0x7f3cdcf40c10>
Traceback (most recent call last):
  File "linear_3078_768.py", line 108, in <module>
    time = Timer(
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 266, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 21, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: ([[tensor([[-0.6219,  0.8298, -0.4536,  ...,  0.7889, -1.7918, -1.1197],
        [ 0.6955,  0.2121,  0.6696,  ..., -0.0877, -3.0250, -1.5446],
        [-0.1544,  0.0722,  0.0944,  ...,  0.1081,  1.2686,  2.1975],
        ...,
        [-0.0977,  0.2086,  1.9484,  ..., -1.4452,  0.1994, -0.8641],
        [ 1.0791, -0.9341, -0.2609,  ...,  0.0928, -0.6365, -2.3033],
        [ 0.8607,  0.5217,  0.9650,  ..., -0.9863,  0.6701, -0.8101]],
       device='cuda:0')]], [[Parameter containing:
tensor([[ 0.0191, -0.0287, -0.0126,  ...,  0.0103, -0.0288,  0.0071],
        [ 0.0085, -0.0320,  0.0338,  ..., -0.0234, -0.0117, -0.0280],
        [-0.0141,  0.0214,  0.0139,  ..., -0.0017, -0.0313,  0.0060],
        ...,
        [ 0.0285,  0.0203,  0.0234,  ..., -0.0324,  0.0345, -0.0295],
        [-0.0202, -0.0229, -0.0316,  ..., -0.0042, -0.0245, -0.0032],
        [ 0.0034,  0.0204, -0.0226,  ..., -0.0191, -0.0272,  0.0259]],
       device='cuda:0', requires_grad=True)]], [tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')], [[None]]), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7f3c30385790>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7f3b9d2b0430>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7f3ce1c17ca0>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
