Get devices for measurement successfully!
#### # Linerar 32 3072 768
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_32_3072_output_0_32_768_in_features_3072_out_features_768.json
#### Find tuned kernel, pass
<function CUDACompiler.create_raw.<locals>.func at 0x7fa701f57790>
Traceback (most recent call last):
  File "linear_3078_768.py", line 100, in <module>
    time = Timer(
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 266, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 21, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: (tensor([[-0.6939, -0.5671, -2.5943,  ...,  0.0907, -0.1979, -0.1061],
        [ 0.4489, -0.1384, -0.2599,  ..., -1.4923, -0.1575,  0.6880],
        [ 0.9134,  0.5363,  1.2198,  ...,  0.4072,  1.0315, -0.1044],
        ...,
        [ 1.0985, -0.4672, -1.6095,  ..., -0.6384,  1.4414,  1.5213],
        [ 1.0942,  0.7385,  1.5221,  ...,  0.7582,  0.5481,  0.4187],
        [ 0.2789, -1.8439,  0.1520,  ..., -0.7698,  0.4385, -1.2696]],
       device='cuda:0'), Parameter containing:
tensor([[-7.4683e-03,  2.4630e-03, -9.9138e-03,  ...,  7.1320e-03,
         -6.1104e-04,  1.4761e-02],
        [-1.5425e-02,  1.7354e-03,  1.5556e-02,  ..., -1.2228e-02,
         -4.4478e-04, -1.0961e-02],
        [ 1.0991e-02, -2.6300e-03,  5.6342e-03,  ..., -2.9472e-03,
          8.4646e-04, -1.0305e-02],
        ...,
        [-9.9132e-03, -7.4193e-03,  8.2246e-05,  ...,  1.0987e-03,
          3.9234e-03, -1.2560e-02],
        [ 2.9787e-03,  3.2801e-03, -7.3573e-03,  ..., -7.1247e-03,
          2.0266e-03, -1.8558e-03],
        [-1.4171e-02, -1.5522e-02, -1.0970e-02,  ..., -1.7218e-02,
         -1.2057e-02,  1.2533e-02]], device='cuda:0', requires_grad=True), tensor([[-1.4996e+08,  4.5794e-41,  4.2195e+31,  ...,  1.7466e+19,
          4.4647e+30,  1.2179e-14],
        [ 9.3346e-15,  5.4275e-14,  7.1546e+22,  ...,  4.5436e+30,
          2.6800e+20,  6.4288e+16],
        [ 9.3346e-15,  7.5555e+31,  4.6042e+30,  ...,  6.7419e+22,
          4.5972e+24,  1.6930e+22],
        ...,
        [ 1.4333e-19,  2.6394e-06,  4.9108e-14,  ...,  6.4288e+16,
          9.3346e-15,  7.5555e+31],
        [ 4.6042e+30,  9.3545e+05,  1.4155e+34,  ...,  7.6196e+17,
          1.9827e+29,  6.7111e+22],
        [ 1.7446e+22,  1.7703e+31,  7.1538e+22,  ...,  1.4155e+34,
          1.8567e-01,  1.4331e-19]], device='cuda:0'), None), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7fa7a00dd700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7fa701f353a0>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7fa84689cc10>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
