Get devices for measurement successfully!
#### # Linerar 192 4096 16384
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
#### Find tuned kernel, pass
------------make_jit_kernel@factory.py-----------------
objective_func:fastest
-----------------make_kernel@ModuleBase---------------------
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
-----------init@HorizFusedKernel-------------
-------------initialize@HorizFusedKernel-------------
self.device_args['placeholder_0, placeholder1_0, T_matmul_NT_0', 'placeholder_1, placeholder1_1, T_matmul_NT_1']
self.shm_sizes[8192]
self.min_blocks_per_sm:1
self.blockidx_x:2048
-----------------get_code@GlobalKernel---------------------
--------------------------------------
processed_template_fname:/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/kernel_template/processed_Linear__in.cu
-------------generate_kernel@CUDACompiler---------------
-------------global@CUDACompiler---------------
kernel_type:horiz_fuse
__ctx__0
Traceback (most recent call last):
  File "linear_4096_16384.py", line 116, in <module>
    linear_kernel(x, weight, y)
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 22, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: (tensor([[ 1.0703,  0.1912,  1.6761,  ..., -0.6140,  1.0334, -0.7613],
        [-0.9045, -0.4509,  1.3966,  ..., -1.7078,  0.8864,  1.3006],
        [ 0.1743,  1.8172, -0.3425,  ...,  0.6705, -1.1721, -0.1805],
        ...,
        [-0.0857, -1.2689, -0.0160,  ..., -1.9476,  0.9200,  0.6102],
        [-0.0598,  0.6887, -0.2266,  ..., -2.2172, -0.8672,  1.0889],
        [ 1.2477,  0.1062,  0.2736,  ...,  0.3859,  0.7828, -0.0552]],
       device='cuda:0'), [Parameter containing:
tensor([[ 0.0153, -0.0053, -0.0065,  ...,  0.0105,  0.0004, -0.0137],
        [-0.0037,  0.0055,  0.0002,  ..., -0.0130,  0.0055,  0.0093],
        [-0.0048, -0.0050,  0.0068,  ..., -0.0040, -0.0016, -0.0052],
        ...,
        [ 0.0138, -0.0131,  0.0077,  ..., -0.0090, -0.0106,  0.0072],
        [-0.0108, -0.0075,  0.0107,  ..., -0.0033,  0.0037, -0.0011],
        [-0.0095, -0.0132,  0.0001,  ..., -0.0081, -0.0102, -0.0089]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 0.0153, -0.0053, -0.0065,  ...,  0.0105,  0.0004, -0.0137],
        [-0.0037,  0.0055,  0.0002,  ..., -0.0130,  0.0055,  0.0093],
        [-0.0048, -0.0050,  0.0068,  ..., -0.0040, -0.0016, -0.0052],
        ...,
        [ 0.0138, -0.0131,  0.0077,  ..., -0.0090, -0.0106,  0.0072],
        [-0.0108, -0.0075,  0.0107,  ..., -0.0033,  0.0037, -0.0011],
        [-0.0095, -0.0132,  0.0001,  ..., -0.0081, -0.0102, -0.0089]],
       device='cuda:0', requires_grad=True)], tensor([[ 0.9494, -0.2499, -0.3580,  ..., -0.0188,  0.1617, -0.7861],
        [ 0.9838, -1.7589,  0.5233,  ...,  0.3820,  2.1310, -1.6829],
        [-0.4288, -0.5248, -0.6345,  ...,  0.2744,  0.7926, -0.0520],
        ...,
        [ 1.0648,  0.6741,  1.7986,  ...,  1.0276,  0.1719,  0.1638],
        [-0.4408,  0.2670,  1.7478,  ..., -1.1518, -0.8559,  1.9774],
        [ 1.0739, -0.6891, -0.8041,  ..., -0.9003,  2.0402,  0.8090]],
       device='cuda:0')), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7fa11b8b9a60>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7fa10a95f700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7fa25e9caf70>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
